# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c9a9d0d62bea188cace86bb4d20ff304d05b24919c76b32d51cce66dd6bfe4a2054d5b2e7fcd48e952dc8b5097b5c86454c0616fd40c429793fbe6ae0abffe3

test:
  secret_key_base: a2e3b98b9e86cd4ceddbb60a166fe3c8f9506d7bb55cfe5c94dfeffcc3a5d6881baeef2918368139b5d55f1031611b8c92dd1499f628eb70f0f3d9b350dcea3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
